### ISSUE TITLE
Github tasks that return results are double encoding the json payload

### ISSUE THREAD

**Issue by morarucostel** [boomerang-io/worker.flow#32]
**Describe the bug**
Github tasks that return results (parameters or in file path) are encoding twice the json payload, making the result into a non valid JSON content. 
In the workflow, following such a github task, if you add the `JSON file to property` it will fail due to the non-valid json content. 

Github Tasks being affected:
```
Invite User to Organization
Get Github Repository
Invite Member to Team
Create Team in Organisation
Get Team in Organization
Get All Teams in Organization
Get Organization Info
Get All Organizations
Find Repositories in Organization
```

**To Reproduce**
Create a workflow with `Get Github Repository` configured to save the result in a file and a `JSON file to property` task to pick-up a value from the file. It will fail due to the invalid json content.

**Expected behavior**
The `JSON file to property` task should be able to read from the github result task.

**Environment (please complete the following information):**

- Flow 3.3

**Additional context**

**Comment by tlawrie** [comment]
Hi @morarucostel is this because the setOutput() function is also doing a JSON.stringify on file save?

And does the utils.setOutputParameters() json stringify?

The reason I ask is to determine/clarify where best to remove the JSON stringify?

**Comment by tlawrie** [comment]
Also good find 👍

**Comment by morarucostel** [comment]
Hey @tlawrie , correct. 
So, one JSON.stringify was done in the task specific method, like inside the github.js and another one in the `worker.interfaces` in the utils.
https://github.com/boomerang-io/worker.interfaces/blob/main/packages/core/src/utils.js#L206

The PR removes the JSON.stringify from the github since tthe utils one is a common for all other tasks, ours and other future extensions from contributors.
