### ISSUE TITLE
Refactor - Send Email with Sendgrid

### ISSUE THREAD

**Issue by florentinvintila** [boomerang-io/worker.flow#46]
Things to improve:

It integrates with Sendgrid and it uses sendgrid/client lib to send the email. Needs to check the response received from Sendgrid, to mark the task if it is a success or not,
An error message must always be present in the logs before closing a task with failure (including when the response from Sendgrid states that the email was not sent, any other non 2xx status).
Validate all the input parameters including the non mandatory ones if they are provided.
Remove the log.sys that outputs the client's apikey.

**Comment by tlawrie** [comment]
Added to the Flow Project and Release 3.6.1

**Comment by tlawrie** [comment]
@timrbula to follow up whether this makes it into 3.7.0
