### ISSUE TITLE
For non-2xx returned calls the "HTTP Execute Call" task the response is not exposed. 

### ISSUE THREAD

**Issue by morarucostel** [boomerang-io/worker.flow#57]
**Describe the bug**
The `Execute Advanced HTTP Call` is not exposing the response and statusCode for the "failed" calls. If you have a server endpoint responding with 400 and a content, the task doesn't output these values as result. 
In addition the task should print in the logs the return code and content of all the calls, during the retrial attempts. 

**To Reproduce**
 - Create a workflow with `Execute Advanced HTTP Call` task. Configure the task to call the `https://httpstat.us/400` endpoint. 
 - Run the workflow. 
 - The task results don't show the values, they are set on null, even though the server end-point is returning 400 with response body.

**Expected behavior**
The task should continue to be considered as failed but since the server returns a response and a HTTP status value, these values needs to come part of the task output parameters.

**Screenshots**
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/13904499/156342792-e081c57b-d302-4e4e-9b1e-b6fc2779b3d8.png">

**Environment (please complete the following information):**

- OS: NA
- Browser all
- Version worker.flow v2.10.20

**Additional context**

**Comment by tlawrie** [comment]
Hi @morarucostel I see you reopened this one. Is something more needed?
