### ISSUE TITLE
Send PostMarkEmail Task has incorrect validation

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/worker.flow#58]
The validation prior to the latest worker was an && not an ||. Its meant to be checkinf if **both** fields are empty.

Change can be seen in this PR https://github.com/boomerang-io/worker.flow/pull/47/files in the mail.js file.

**Comment by morarucostel** [comment]
Hi @tlawrie , 
I'm trying to find the changes you are pointing to. Is this the one?
The old code:
```
    // Validate input
    if (!token || !from || !to) {
      log.err("A required parameter has not been provided. Please check your parameters and try again.", "\nToken: " + token, "\nFrom: " + from, "\nTo: " + to);
```
which was replaced by:
```
    if (checkParameters({ token, from, to })) {
      log.err(`A required parameter has not been provided. Please check your parameters and try again.`);
      process.exit(1);
    }
```

**Comment by tlawrie** [comment]
Hey @morarucostel . Its a few lines lower.

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/16438811/158700239-d9a0bf41-838c-4c09-bad0-5763a5107918.png">
