### ISSUE TITLE
System retry for HTTP Task on special exceptions

### ISSUE THREAD

**Issue by florentinvintila** [boomerang-io/worker.flow#78]
Retry the HTTP request in case some special exceptions are triggered by the system such as CONNREFUSED, DNS-TIMEOUT, EAI_AGAIN ( similar to DDoS ) and ETIMEDOUT.

**Comment by tlawrie** [comment]
@florentinvintila @amhudson is there a loader update for the new default worker version?

**Comment by amhudson** [comment]
> @florentinvintila @amhudson is there a loader update for the new default worker version?

no, but let me know the new version and I can get into the loader

**Comment by tlawrie** [comment]
@florentinvintila do you know the new version of the flow worker to go into the loader?
