### ISSUE TITLE
Internal routes ERR_INVALID_PROTOCOL

### ISSUE THREAD

**Issue by florentinvintila** [boomerang-io/worker.flow#83]
For internal routes that have HTTP protocol an error is triggered with `HTTP Promise error: TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"`.
Similar behaviour to HTTPS protocol calling HTTP url.

**Comment by gchickma** [comment]
Verified in IBM development & testing environments
